version: '3.9'
services: 
    mongodb: 
      image: 'mongo:4.4.6'
    
      container_name: 'meu-mongo'

      networks:
        - transferencia
    
    aplicativo_books:
      image: aluradocker/alura-books:1.0

      container_name: aplicacao_books

      ports:
        - 3000:3000

      networks:
        - transferencia
      depends_on:
        - mongodb
    
networks:
  transferencia: 
    driver: bridge

